# Generated by Django 2.1.2 on 2018-10-15 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('TIFF', '0001_initial'),
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='唯一主键')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='处理时间')),
                ('tiff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='TIFF.Image', verbose_name='大图')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profile.Profile', verbose_name='名称')),
            ],
            options={
                'verbose_name_plural': '任务分配信息',
                'verbose_name': '任务分配信息',
            },
        ),
    ]
