# Generated by Django 2.0.6 on 2018-11-08 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Profile', '0002_profile_nickname'),
        ('TIFF', '0004_image_case_no'),
        ('PathologyType', '0003_auto_20181030_1649'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='唯一主键')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='处理时间')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PathologyType.Type', verbose_name='用户答案')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TIFF.Image', verbose_name='关联病理图像')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profile.Profile', verbose_name='关联用户')),
            ],
            options={
                'verbose_name': '竞猜信息',
                'verbose_name_plural': '竞猜信息',
            },
        ),
    ]
