# Generated by Django 2.0.6 on 2018-10-30 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserType', '0002_auto_20181028_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertype',
            name='description',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='描述'),
        ),
    ]
