# Generated by Django 2.0.6 on 2018-11-15 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Question', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='标题'),
        ),
    ]
