# Generated by Django 2.0.6 on 2018-11-15 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Question', '0002_auto_20181115_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TIFF.Image', unique=True, verbose_name='关联病理图像'),
        ),
    ]
