# Generated by Django 2.0.6 on 2018-11-17 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Question', '0004_auto_20181115_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.OneToOneField(limit_choices_to={'is_valid': 'YES'}, on_delete=django.db.models.deletion.CASCADE, to='TIFF.Image', verbose_name='关联病理图像'),
        ),
    ]
