# Generated by Django 2.0.6 on 2018-10-28 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('TIFF', '0001_initial'),
        ('PathologyType', '0002_auto_20181028_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='唯一主键')),
                ('x', models.FloatField(verbose_name='标注点左上角坐标-x')),
                ('y', models.FloatField(verbose_name='标注点左上角坐标-y')),
                ('w', models.FloatField(verbose_name='标注点细胞宽度-w')),
                ('h', models.FloatField(verbose_name='标注点细胞高度-h')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='处理时间')),
                ('cell_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PathologyType.Type', verbose_name='细胞类别')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TIFF.Image', verbose_name='关联病理图像')),
            ],
            options={
                'verbose_name': '标注信息',
                'verbose_name_plural': '标注信息',
            },
        ),
    ]
