# Generated by Django 2.0.6 on 2018-11-07 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Label', '0002_auto_20181107_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='cell',
            name='accuracy',
            field=models.FloatField(blank=True, null=True, verbose_name='相似度'),
        ),
    ]
