# Generated by Django 2.0.6 on 2018-11-07 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Label', '0003_cell_accuracy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cell',
            name='cell_type',
            field=models.CharField(max_length=32, verbose_name='细胞类别'),
        ),
    ]
