# Generated by Django 2.0.6 on 2018-10-30 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TIFF', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='progress',
            field=models.CharField(default='-', max_length=16, verbose_name='当前算法处理进度'),
        ),
        migrations.AlterField(
            model_name='image',
            name='result_auto',
            field=models.CharField(default='-', max_length=32, verbose_name='算法诊断结果'),
        ),
        migrations.AlterField(
            model_name='image',
            name='result_manual',
            field=models.CharField(default='-', max_length=32, verbose_name='医生诊断结果'),
        ),
        migrations.AlterField(
            model_name='image',
            name='result_status',
            field=models.CharField(default='-', max_length=32, verbose_name='标准诊断结果'),
        ),
    ]
