# Generated by Django 2.0.6 on 2018-10-30 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TIFF', '0002_auto_20181030_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='remark',
            field=models.TextField(blank=True, null=True, verbose_name='故障原因'),
        ),
        migrations.AddField(
            model_name='image',
            name='status',
            field=models.CharField(choices=[('CREATED', '待处理'), ('SUCCESS', '处理完成'), ('FAIL', '处理失败'), ('DELETED', '已删除')], default='CREATED', max_length=16, verbose_name='状态'),
        ),
    ]
