# Generated by Django 2.0.6 on 2018-11-01 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TIFF', '0003_auto_20181030_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='case_no',
            field=models.CharField(default='-', max_length=64, verbose_name='病理号'),
        ),
    ]
