# Generated by Django 2.0.6 on 2018-11-13 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TIFF', '0004_image_case_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='result_auto',
            field=models.CharField(default='-', max_length=64, verbose_name='算法诊断结果'),
        ),
        migrations.AlterField(
            model_name='image',
            name='result_manual',
            field=models.CharField(default='-', max_length=64, verbose_name='医生诊断结果'),
        ),
        migrations.AlterField(
            model_name='image',
            name='result_status',
            field=models.CharField(default='-', max_length=64, verbose_name='标准诊断结果'),
        ),
    ]
