# Generated by Django 2.0.6 on 2018-11-15 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TIFF', '0005_auto_20181113_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='progress',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='当前算法处理进度'),
        ),
        migrations.AlterField(
            model_name='image',
            name='result_auto',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='算法诊断结果'),
        ),
        migrations.AlterField(
            model_name='image',
            name='result_manual',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='医生诊断结果'),
        ),
        migrations.AlterField(
            model_name='image',
            name='result_status',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='标准诊断结果'),
        ),
    ]
