# Generated by Django 2.0.6 on 2018-11-17 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TIFF', '0006_auto_20181115_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='is_valid',
            field=models.CharField(choices=[('YES', '是'), ('NO', '否')], default='YES', max_length=16, verbose_name='是否显示'),
        ),
    ]
