# Generated by Django 2.0.6 on 2018-11-08 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nickname',
            field=models.CharField(default=123, max_length=64, verbose_name='昵称'),
            preserve_default=False,
        ),
    ]
