# Generated by Django 2.1.2 on 2018-10-15 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='唯一主键')),
                ('name', models.CharField(max_length=64, verbose_name='名称')),
                ('description', models.CharField(max_length=1024, verbose_name='描述')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='处理时间')),
            ],
            options={
                'verbose_name_plural': '病理类型',
                'verbose_name': '病理类型',
            },
        ),
    ]
