# Generated by Django 2.0.6 on 2018-10-28 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PathologyType', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='color',
            field=models.CharField(default='#aa0000', max_length=16, verbose_name='显示颜色'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='type',
            name='description',
            field=models.CharField(max_length=128, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(max_length=32, verbose_name='名称'),
        ),
    ]
